//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocGia
    {
        public string MaDG { get; set; }
        public string TenDG { get; set; }
        public string DiaChi { get; set; }
        public string NgheNghiep { get; set; }
        public string Sdt { get; set; }
        public string LoaiDG { get; set; }
        public System.DateTime ThoiHan { get; set; }
    }
}
