//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sach
    {
        public string MaSach { get; set; }
        public string TenSach { get; set; }
        public string TenTG { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string MaTL { get; set; }
    
        public virtual TheLoai TheLoai { get; set; }
    }
}
